jobs:
- name: Checkout 
  uses: actions/checkout@v3
  with:
    repository: sky1wnDO/ci-cd-piplines
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GPG_KEY }}
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
- name: executing remote ssh commands using ssh key
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.IP }}
    username: student
    key: ${{ secrets.SSH }}
          
          
        
          
