jobs:
 - name: Checkout 
   uses: actions/checkout@v3
   with:
     repository: sky1wnDO/ci-cd-piplines
- name: ci
on:
   push:
     branches:
       - 'main'

 jobs:
   docker:
     runs-on: ubuntu-latest
     steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: sky1wnDO
          password: ${{ secrets.GPG }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: user/app:latest
name: executing remote ssh commands using ssh key
uses: appleboy/ssh-action@master
with:
    host: ${{ secrets.IP }}
    username: student
    key: ${{ secrets.SSH }}
          
          
        
          
